// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCut-PPtTQvwWg6cQh0u-WkcryKoBh6QsY',
    appId: '1:1020103883992:web:0458fefb7ddd41eccdebad',
    messagingSenderId: '1020103883992',
    projectId: 'flutterfood-8ef11',
    authDomain: 'flutterfood-8ef11.firebaseapp.com',
    storageBucket: 'flutterfood-8ef11.appspot.com',
    measurementId: 'G-4SZ498MP6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGgqw4DwPty5rvzEciDNuyPMxa4kwqkiM',
    appId: '1:1020103883992:android:677450cbf74da915cdebad',
    messagingSenderId: '1020103883992',
    projectId: 'flutterfood-8ef11',
    storageBucket: 'flutterfood-8ef11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9zQO2kuYBHtwXatE8UvM9XBGLaokvMaw',
    appId: '1:1020103883992:ios:4c3cebcd6aa63c80cdebad',
    messagingSenderId: '1020103883992',
    projectId: 'flutterfood-8ef11',
    storageBucket: 'flutterfood-8ef11.appspot.com',
    iosBundleId: 'com.example.flutterFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9zQO2kuYBHtwXatE8UvM9XBGLaokvMaw',
    appId: '1:1020103883992:ios:4c3cebcd6aa63c80cdebad',
    messagingSenderId: '1020103883992',
    projectId: 'flutterfood-8ef11',
    storageBucket: 'flutterfood-8ef11.appspot.com',
    iosBundleId: 'com.example.flutterFood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCut-PPtTQvwWg6cQh0u-WkcryKoBh6QsY',
    appId: '1:1020103883992:web:fe5e2fc98606e5b1cdebad',
    messagingSenderId: '1020103883992',
    projectId: 'flutterfood-8ef11',
    authDomain: 'flutterfood-8ef11.firebaseapp.com',
    storageBucket: 'flutterfood-8ef11.appspot.com',
    measurementId: 'G-7332J2S162',
  );
}
